Add files via upload

diff --git a/.github/workflows/Build-SukiSU2.yml b/.github/workflows/Build-SukiSU2.yml
--- a/.github/workflows/Build-SukiSU2.yml
+++ b/.github/workflows/Build-SukiSU2.yml
@@ -1,4 +1,4 @@
-name: Build OnePlus_Kernel改
+name: Build OnePlus_Kernel
 on:
   workflow_dispatch:
     inputs:
@@ -184,27 +184,11 @@ jobs:
           echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
 
-          if [ "${{ github.event.inputs.KERNEL_VERSION }}" != "6.6" ] && [ "${{ github.event.inputs.KERNEL_VERSION }}" != "5.10" ]; then
-            sed -i 's/CONFIG_ZRAM=m/CONFIG_ZRAM=y/g' ./common/arch/arm64/configs/gki_defconfig
-            sed -i 's/CONFIG_ZSMALLOC=m/CONFIG_ZSMALLOC=y/g' ./common/arch/arm64/configs/gki_defconfig
-            sed -i 's/CONFIG_MODULE_SIG=y/CONFIG_MODULE_SIG=n/g' ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_ZRAM_WRITEBACK=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
-          fi
-
-          if [ "${{ github.event.inputs.KERNEL_VERSION }}" = "6.6" ]; then
-            echo "CONFIG_ZSMALLOC=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_ZRAM_WRITEBACK=y" >> ./common/arch/arm64/configs/gki_defconfig
-            sed -i 's/CONFIG_ZRAM=m/CONFIG_ZRAM=y/g' ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_ZRAM_WRITEBACK=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
-            echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
-          fi
+          # 添加压缩算法配置
+          echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
 
           sed -i 's/check_defconfig//' ./common/build.config.gki
 
@@ -217,22 +201,6 @@ jobs:
       - name: Build kernel
         run: |
           cd kernel_workspace
-          
-          # 第一次构建（生成模块列表）
-          if [[ "${{ github.event.inputs.CPU }}" == "sm8650" || "${{ github.event.inputs.CPU }}" == "sm8750" ]]; then
-            ./kernel_platform/build_with_bazel.py -t ${{ github.event.inputs.CPUD }} gki --action_env=KSU_VERSION || true
-          else
-            LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} gki || true
-          fi
-          
-          # 更新模块列表
-          if [ -f "./kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/gki_kernel/common/modules.order" ]; then
-            cp ./kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/gki_kernel/common/modules.order ./kernel_platform/common/android/gki_aarch64_modules
-            git -C ./kernel_platform/common add android/gki_aarch64_modules
-            git -C ./kernel_platform/common commit -m "Update gki_aarch64_modules" || true
-          fi
-          
-          # 正式构建
           if [[ "${{ github.event.inputs.CPU }}" == "sm8650" || "${{ github.event.inputs.CPU }}" == "sm8750" ]]; then
             ./kernel_platform/build_with_bazel.py -t ${{ github.event.inputs.CPUD }} gki --action_env=KSU_VERSION
           else
@@ -246,7 +214,7 @@ jobs:
 
           dir1="./kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-gki/dist/"
           dir2="./kernel_workspace/kernel_platform/common/out/arch/arm64/boot/"
-         dir3=".kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/gki_kernel/common/"
+          dir3="./kernel_workspace/kernel_platform/out/msm-kernel-kalama-gki/gki_kernel/common/"
           target1="./AnyKernel3/"
           target2="./kernel_workspace/kernel"
 
@@ -258,18 +226,18 @@ jobs:
               cp "$dir2"Image "$target1"
               cp "$dir2"Image "$target2"
             else
-             if find "$dir3" -name "Image" | grep -q "Image"; then
-              cp "$dir3"Image "$target1"
-              cp "$dir3"Image "$target2"
-            else
-              image_path=$(find "./kernel_workspace/kernel_platform/common/out/" -name "Image" | head -n 1)
-              if [ -n "$image_path" ]; then
-                cp "$image_path" "$target1"
-                cp "$image_path" "$target2"
-                cp "$image_path" "$target3"
+              if find "$dir3" -name "Image" | grep -q "Image"; then
+                cp "$dir3"Image "$target1"
+                cp "$dir3"Image "$target2"
               else
-                echo "::error::未找到 Image 文件"
-                exit 1
+                image_path=$(find "./kernel_workspace/kernel_platform/common/out/" -name "Image" | head -n 1)
+                if [ -n "$image_path" ]; then
+                  cp "$image_path" "$target1"
+                  cp "$image_path" "$target2"
+                else
+                  echo "::error::未找到 Image 文件"
+                  exit 1
+                fi
               fi
             fi
           fi
@@ -290,4 +258,4 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: zram.ko_KernelSU_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
-          path: drivers/block/zram/zram.ko
+          path: kernel_workspace/kernel_platform/common/drivers/block/zram/zram.ko
